## numpy functions

### np.sort

In [155]:
import numpy as np
a = np.random.randint(1,100,15)
print(a)
print(np.sort(a))

[60 44 81 92 77 70 34 80 71 87 83 48 78 21 52]
[21 34 44 48 52 60 70 71 77 78 80 81 83 87 92]


In [156]:
b = np.random.randint(1,100,24).reshape(6,4)
print(b)
print(np.sort(b, axis=0)) # column wise sorting

[[57 44 93 99]
 [ 9 97 56 49]
 [17 78 23 74]
 [11 31 21 79]
 [73 33 44 23]
 [30 57 41 40]]
[[ 9 31 21 23]
 [11 33 23 40]
 [17 44 41 49]
 [30 57 44 74]
 [57 78 56 79]
 [73 97 93 99]]


### np.append

In [157]:
np.append(a, 200)

array([ 60,  44,  81,  92,  77,  70,  34,  80,  71,  87,  83,  48,  78,
        21,  52, 200])

In [158]:
b

array([[57, 44, 93, 99],
       [ 9, 97, 56, 49],
       [17, 78, 23, 74],
       [11, 31, 21, 79],
       [73, 33, 44, 23],
       [30, 57, 41, 40]])

In [159]:
np.append(b, np.ones((b.shape[0],1)), axis=1)

array([[57., 44., 93., 99.,  1.],
       [ 9., 97., 56., 49.,  1.],
       [17., 78., 23., 74.,  1.],
       [11., 31., 21., 79.,  1.],
       [73., 33., 44., 23.,  1.],
       [30., 57., 41., 40.,  1.]])

### np.concatenate

In [160]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)
np.concatenate((c,d), axis=0)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### np.unique

In [161]:
# how to find dimentions : numpy_array.shape
a = np.arange(15)
np.expand_dims(a, axis=1) # this one is 2D array but a is 1D array you can check with a.shape

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

### np.where

In [162]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [163]:
# find indices where values are greater than 50
np.where(a>5)

(array([ 6,  7,  8,  9, 10, 11, 12, 13, 14]),)

In [164]:
# replace values which is grater then 50 with 0
np.where(a>5,0,a) # a[np.where(a>5)] = 0

np.where(a%2==0,0,a)

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0])

### np.argmax

In [165]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [166]:
np.argmax(a)

14

In [167]:
b

array([[57, 44, 93, 99],
       [ 9, 97, 56, 49],
       [17, 78, 23, 74],
       [11, 31, 21, 79],
       [73, 33, 44, 23],
       [30, 57, 41, 40]])

In [168]:
np.argmax(b, axis=0)

array([4, 1, 0, 0])

### np.argmin

In [169]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [170]:
np.argmin(a)

0

### np.cumsum

In [171]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [172]:
np.cumsum(a)

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105])

In [173]:
b

array([[57, 44, 93, 99],
       [ 9, 97, 56, 49],
       [17, 78, 23, 74],
       [11, 31, 21, 79],
       [73, 33, 44, 23],
       [30, 57, 41, 40]])

In [174]:
np.cumsum(b, axis=0)

array([[ 57,  44,  93,  99],
       [ 66, 141, 149, 148],
       [ 83, 219, 172, 222],
       [ 94, 250, 193, 301],
       [167, 283, 237, 324],
       [197, 340, 278, 364]])

### np.cumprod

In [175]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [176]:
np.cumprod(a)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### np.percentile

In [177]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [178]:
np.percentile(a, 50)

7.0

In [179]:
b

array([[57, 44, 93, 99],
       [ 9, 97, 56, 49],
       [17, 78, 23, 74],
       [11, 31, 21, 79],
       [73, 33, 44, 23],
       [30, 57, 41, 40]])

In [180]:
np.percentile(b, 100)

99.0

### np.histogram

In [181]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [182]:
np.histogram(a, bins=[0,50,100])

(array([15,  0]), array([  0,  50, 100]))

In [183]:
b

array([[57, 44, 93, 99],
       [ 9, 97, 56, 49],
       [17, 78, 23, 74],
       [11, 31, 21, 79],
       [73, 33, 44, 23],
       [30, 57, 41, 40]])

In [184]:
np.histogram(b, bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 2, 3, 3, 5, 3, 0, 4, 0, 3]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

### np.corrcoef

In [185]:
salary = [10000, 20000, 30000, 40000, 50000]
experience = [1, 2, 3, 4, 5]

np.corrcoef(salary, experience)

array([[1., 1.],
       [1., 1.]])

### np.isin

In [186]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [187]:
items = [2,4,6,8,10,12,14,16,18,20]

a[np.isin(a, items)]

array([ 2,  4,  6,  8, 10, 12, 14])

### np.flip

In [188]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [189]:
np.flip(a)

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [190]:
b

array([[57, 44, 93, 99],
       [ 9, 97, 56, 49],
       [17, 78, 23, 74],
       [11, 31, 21, 79],
       [73, 33, 44, 23],
       [30, 57, 41, 40]])

In [191]:
np.flip(b, axis=1)

array([[99, 93, 44, 57],
       [49, 56, 97,  9],
       [74, 23, 78, 17],
       [79, 21, 31, 11],
       [23, 44, 33, 73],
       [40, 41, 57, 30]])

### np.put

In [192]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [193]:
np.put(a, 0, 10)
print(a)

[10  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


### np.delete

In [200]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [199]:
np.delete(a, 2)

array([10,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])