## numpy functions

### np.sort

In [ ]:
import numpy as np
a = np.random.randint(1,100,15)
print(a)
print(np.sort(a))

[46 63 16  7 42 39 35 33 30 84 12 21 24 18  1]
[ 1  7 12 16 18 21 24 30 33 35 39 42 46 63 84]


In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
print(b)
print(np.sort(b, axis=0)) # column wise sorting

[[88 89 82 32]
 [49 39 40 12]
 [93 59 80 32]
 [60 33 92 10]
 [99 47 59 96]
 [74 50 16 79]]
[[49 33 16 10]
 [60 39 40 12]
 [74 47 59 32]
 [88 50 80 32]
 [93 59 82 79]
 [99 89 92 96]]


### np.append

In [20]:
np.append(a, 200)

array([ 46,  63,  16,   7,  42,  39,  35,  33,  30,  84,  12,  21,  24,
        18,   1, 200])