## numpy functions

### np.sort

In [218]:
import numpy as np
a = np.random.randint(1,100,15)
print(a)
print(np.sort(a))

[94 53 88 18 70 44 31 72 87 78 34 54 74 46 50]
[18 31 34 44 46 50 53 54 70 72 74 78 87 88 94]


In [219]:
b = np.random.randint(1,100,24).reshape(6,4)
print(b)
print(np.sort(b, axis=0)) # column wise sorting

[[95 77 34 57]
 [63 35 88  5]
 [72 58 80 77]
 [34  5 29 49]
 [28 11 42 61]
 [57 79 87 66]]
[[28  5 29  5]
 [34 11 34 49]
 [57 35 42 57]
 [63 58 80 61]
 [72 77 87 66]
 [95 79 88 77]]


### np.append

In [220]:
np.append(a, 200)

array([ 94,  53,  88,  18,  70,  44,  31,  72,  87,  78,  34,  54,  74,
        46,  50, 200])

In [221]:
b

array([[95, 77, 34, 57],
       [63, 35, 88,  5],
       [72, 58, 80, 77],
       [34,  5, 29, 49],
       [28, 11, 42, 61],
       [57, 79, 87, 66]])

In [222]:
np.append(b, np.ones((b.shape[0],1)), axis=1)

array([[95., 77., 34., 57.,  1.],
       [63., 35., 88.,  5.,  1.],
       [72., 58., 80., 77.,  1.],
       [34.,  5., 29., 49.,  1.],
       [28., 11., 42., 61.,  1.],
       [57., 79., 87., 66.,  1.]])

### np.concatenate

In [223]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)
np.concatenate((c,d), axis=0)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### np.unique

In [224]:
# how to find dimentions : numpy_array.shape
a = np.arange(15)
np.expand_dims(a, axis=1) # this one is 2D array but a is 1D array you can check with a.shape

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

### np.where

In [225]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [226]:
# find indices where values are greater than 50
np.where(a>5)

(array([ 6,  7,  8,  9, 10, 11, 12, 13, 14]),)

In [227]:
# replace values which is grater then 50 with 0
np.where(a>5,0,a) # a[np.where(a>5)] = 0

np.where(a%2==0,0,a)

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0])

### np.argmax

In [228]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [229]:
np.argmax(a)

14

In [230]:
b

array([[95, 77, 34, 57],
       [63, 35, 88,  5],
       [72, 58, 80, 77],
       [34,  5, 29, 49],
       [28, 11, 42, 61],
       [57, 79, 87, 66]])

In [231]:
np.argmax(b, axis=0)

array([0, 5, 1, 2])

### np.argmin

In [232]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [233]:
np.argmin(a)

0

### np.cumsum

In [234]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [235]:
np.cumsum(a)

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105])

In [236]:
b

array([[95, 77, 34, 57],
       [63, 35, 88,  5],
       [72, 58, 80, 77],
       [34,  5, 29, 49],
       [28, 11, 42, 61],
       [57, 79, 87, 66]])

In [237]:
np.cumsum(b, axis=0)

array([[ 95,  77,  34,  57],
       [158, 112, 122,  62],
       [230, 170, 202, 139],
       [264, 175, 231, 188],
       [292, 186, 273, 249],
       [349, 265, 360, 315]])

### np.cumprod

In [238]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [239]:
np.cumprod(a)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### np.percentile

In [240]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [241]:
np.percentile(a, 50)

7.0

In [242]:
b

array([[95, 77, 34, 57],
       [63, 35, 88,  5],
       [72, 58, 80, 77],
       [34,  5, 29, 49],
       [28, 11, 42, 61],
       [57, 79, 87, 66]])

In [243]:
np.percentile(b, 100)

95.0

### np.histogram

In [244]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [245]:
np.histogram(a, bins=[0,50,100])

(array([15,  0]), array([  0,  50, 100]))

In [246]:
b

array([[95, 77, 34, 57],
       [63, 35, 88,  5],
       [72, 58, 80, 77],
       [34,  5, 29, 49],
       [28, 11, 42, 61],
       [57, 79, 87, 66]])

In [247]:
np.histogram(b, bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([2, 1, 2, 3, 2, 3, 3, 4, 3, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

### np.corrcoef

In [248]:
salary = [10000, 20000, 30000, 40000, 50000]
experience = [1, 2, 3, 4, 5]

np.corrcoef(salary, experience)

array([[1., 1.],
       [1., 1.]])

### np.isin

In [249]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [250]:
items = [2,4,6,8,10,12,14,16,18,20]

a[np.isin(a, items)]

array([ 2,  4,  6,  8, 10, 12, 14])

### np.flip

In [251]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [252]:
np.flip(a)

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [253]:
b

array([[95, 77, 34, 57],
       [63, 35, 88,  5],
       [72, 58, 80, 77],
       [34,  5, 29, 49],
       [28, 11, 42, 61],
       [57, 79, 87, 66]])

In [254]:
np.flip(b, axis=1)

array([[57, 34, 77, 95],
       [ 5, 88, 35, 63],
       [77, 80, 58, 72],
       [49, 29,  5, 34],
       [61, 42, 11, 28],
       [66, 87, 79, 57]])

### np.put

In [255]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [256]:
np.put(a, 0, 10)
print(a)

[10  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


### np.delete

In [257]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [258]:
np.delete(a, 2)

array([10,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### set functions
#### np.union1d
#### np.intersect1d
#### np.setdiff1d
#### np.setxor1d
#### np.in1d

In [259]:
# a = np.array([1,2,3,4,5])
# b = np.array([3,4,5,6,7])

In [260]:
np.union1d(a,b)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 28, 29, 34,
       35, 42, 49, 57, 58, 61, 63, 66, 72, 77, 79, 80, 87, 88, 95])

In [261]:
np.intersect1d(a,b)

array([ 5, 11])

In [262]:
np.setdiff1d(a,b) # means present in a but in b

array([ 1,  2,  3,  4,  6,  7,  8,  9, 10, 12, 13, 14])

In [263]:
np.setxor1d(a,b)

array([ 1,  2,  3,  4,  6,  7,  8,  9, 10, 12, 13, 14, 28, 29, 34, 35, 42,
       49, 57, 58, 61, 63, 66, 72, 77, 79, 80, 87, 88, 95])

In [264]:
np.in1d(a,1)

array([False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

### np.clip

In [265]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [268]:
np.clip(a, a_min=1, a_max=14)

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 