# Array Attributes

In [4]:
import numpy as np
a1 = np.arange(1, dtype=np.int32)
a2 = np.arange(1, 17, dtype=np.int32).reshape(2,2,2,2)

# print(a1)
# print(a2)
# print(a2.ndim)
# print(a2.shape)
# print(a2.size)
# print(a2.itemsize)
# print(a2.dtype)
# a1.astype(np.float64)
# print(a1.dtype)

# array operations

In [5]:
# scaler operations
a3 = np.arange(1, 13).reshape(3,4)
a4 = np.arange(12,24).reshape(3,4)

# arthematic operatons
# a3 = a3 ** 2

# relational operatons
# a3 == 10

# vector operations
# a3 * a4

# print(a3)
# print(a4)

# array functions

In [6]:
'''
max/min/sum/prod
'''

# np.max(a4)
# np.min(a4)
# np.sum(a4)
# np.prod(a4)

# how to apply these function on column/raw, column = 0, raw = 1.
# np.prod(a3, axis=1)

'''
mean/median/std/var
'''
# np.mean(a3, axis=1)

'''
trignometric functions
'''
# np.tan(a3)

'''
dot product
'''
a5 = np.arange(1, 13).reshape(3,4)
a6 = np.arange(12,24).reshape(4,3)
# np.dot(a5, a6)

'''
log and exponent functions
'''
# np.log(a5)
# np.exp(a5)

'''
round/floor/ceil
'''
a7 = np.random.random((2,3))
# print(a7)
# np.round(a7)
# np.floor(a7)
# np.ceil(a7)


# indexing and slicing

In [7]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(27).reshape(3,3,3)


In [8]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [11]:
# indexing
# a2[1,0]
# a3[1,0,1]

# slicing
# a1[2:5]
# a2[::2, 1::2]
# a2[1, ::3]
# a2[0:2, 1:]
# a3[1, :, :] # do this with a3[1] as well
# a3[2, 1:, 1:]
a3[::2, 0, ::2]

array([[ 0,  2],
       [18, 20]])

# iteration on numpy array

In [12]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [14]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [16]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [17]:
# for i in a3:
#     print(i)

for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# reshaping

In [18]:
# reshape
# a1.reshape(5,2)

# transpose
# a3.transpose()
# a3.T

# ravel
print(a2)
a2.ravel()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# stacking

In [19]:
# horizontal stacking
a4 = np.arange(1, 13).reshape(4,3)
a5 = np.arange(12, 24).reshape(4,3)
# np.hstack((a4,a5))

# vertical stacking
# np.vstack((a4,a5))

# splitting

In [20]:
a4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [21]:
# horizontal splitting
# np.hsplit(a4, 3)

# vertical splitting
np.vsplit(a4, 2)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]