# Array Attributes

In [1]:
import numpy as np
a1 = np.arange(1, dtype=np.int32)
a2 = np.arange(1, 17, dtype=np.int32).reshape(2,2,2,2)

print(a1)
print(a2)
print(a2.ndim)
print(a2.shape)
print(a2.size)
print(a2.itemsize)
print(a2.dtype)
a1.astype(np.float64)
print(a1.dtype)

[0]
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
4
(2, 2, 2, 2)
16
4
int32
int32


# array operations

In [ ]:
# scaler operations
